services:
  postgres:
    container_name: postgres-jp
    build: .
    image: postgres-jp:17
    restart: always
    user: postgres
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init0.sql:/docker-entrypoint-initdb.d/init0.sql
      - ./init1.sh:/docker-entrypoint-initdb.d/init1.sh
    ports:
      - 127.0.0.1:5432:5432
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 10

volumes:
  postgres:
    name: postgres